export default {
  lang_loading_waiting:'Loading, please wait...',
  lang_clear_filter:'Clear Filter Condition',
  lang_empty_data:'No Data',
  lang_ticket_list_no_permission:'You have no authorization to operate, please contact the administrator',
  lang_load_more:'Loading, please wait...',

  lang_status_1:'To Do',
  lang_status_2:'In Progress',
  lang_status_3:'Submitted',
  lang_status_4:'Reverted',
  lang_status_5:'Completed',
  lang_status_6:'Ignored',

  lang_ticket_status_type:['To Do','In Progress','Submitted','Reverted','Completed','Ignored'],
  lang_ticket_name:'Work Name',
  lang_ticket_filter_time:'Time',
  lang_ticket_filter_ok:'confirm',
  lang_ticket_filter_reset:'Reset',
  lang_ticket_filter_status:'Status',
  lang_ticket_filter_start_time:'Start Time',
  lang_ticket_filter_end_time:'End Time',
  lang_ticket_filter_cancel:'Cancel',
  lang_ticket_filter_select_date:'Chose Time',
  lang_ticket_filter_input:'Please input...',
  lang_ticket_clear_filter:'Clear Filter Condition',
  lang_ticket_filter:'Search',

  lang_ticket_detail_log:'Work Logs',
  lang_ticket_detail_add_log:'Create Work Log',
  lang_ticket_detail_edit_log:'Edit Work Log',
  lang_ticket_detail_del_log:'Delete Work Log',
  lang_ticket_detail_create_time:'Create',
  lang_ticket_detail_task:'Description',
  lang_ticket_detail_assets:'Equipment',

  lang_ticket_detail_approved:'Approve',
  lang_ticket_detail_write_log:'Add Work Log',
  lang_ticket_detail_begin_execute:'Execute',
  lang_ticket_detail_submit_ticket:'Submit',
  lang_ticket_log_del_confirm:'Are you sure to delete it？',
  lang_ticket_log_del_img_confirm:'Are you sure to delete it？',
  lang_ticket_log_del_ok:'Delete',
  lang_ticket_detail_share:'Share',
  lang_ticket_detail_edit:'Edit',
  lang_ticket_detail:'Work Details',
  lang_ticket_detail_ignore:'Ignore',
  lang_ticket_detail_ignore_confirm:'It cannot be operated after being ignored.Are you sure to ignore it?',
  lang_ticket_detail_ticketId:'Work ID',
  lang_ticket_submit_invalid:'Unable to submit, please add work log and try again',
  lang_ticket_detail_reject_reason:'Cause of Reverted',
  lang_ticket_execute_toast:'Starting, please add work log',
  lang_ticket_submit_toast:'Submitted Successfully',
  lang_ticket_close_toast:'Completed',
  lang_ticket_close_confirm:'Are you sure to complete it?',

  lang_ticket_detail_change_time:'Edit Execute Time',
  lang_ticket_detail_change_executors:'Edit Executor',

  lang_ticket_diagnose:'Smart Diagnosis Works',

  lang_ticket_to:'to',


  lang_alert_title:'Notice',
  lang_alert_ok:'Ok',

  lang_ticket_select_time_invalid:'The start time cannot be later than the end time',

  lang_toolbar_ok:'Done',
  lang_toolbar_submit:'Submit',

  lang_image_picker_cancel:'Cancel',
  lang_image_picker_accept:'Allow',
  lang_image_picker_accept_msg:'Please allow this App to get access your camera in your phone\'s "Settings"',
  lang_image_picker_access_storage:'Please allow this App to get read and write your storage in your phone\'s "Settings"',
  lang_image_picker_open_photos:'Open the Camera',
  lang_image_picker_from_photos:'Get it from your photo album',
  lang_image_picker_title:'Photo',
  lang_image_picker_access_photos:'Please allow this App to get access your photos in your phone\'s "Settings"',
  lang_image_picker_read_storage:'Please allow this App to access your storage in your phone\'s "Settings"',
  lang_image_picker_no_photos:'No Photos',
  lang_image_take_photo:'Take Photos',

  lang_today:'today',

  lang_network_error:'Failed to load, please check your network setting',
  lang_server_error:'Server exception',
  lang_http_no_content:'No Content',
  lang_http_401:'Unauthorized'
};
