export default {
  lang_loading_waiting: 'Loading, please wait...',
  lang_clear_filter: 'Clear Filter Condition',
  lang_empty_data: 'No Data',
  lang_ticket_list_no_permission: 'You have no authorization to operate, please contact the administrator',
  lang_load_more: 'Loading, please wait...',

  lang_status_1: 'To Do',
  lang_status_2: 'In Progress',
  lang_status_3: 'Submitted',
  lang_status_4: 'Reverted',
  lang_status_5: 'Completed',
  lang_status_6: 'Ignored',

  lang_ticket_status_type: ['To Do', 'In Progress', 'Submitted', 'Reverted', 'Completed', 'Ignored'],
  lang_ticket_name: 'Work Name',
  lang_ticket_filter_time: 'Time',
  lang_ticket_filter_ok: 'confirm',
  lang_ticket_filter_reset: 'Reset',
  lang_ticket_filter_status: 'Status',
  lang_ticket_filter_start_time: 'Start Time',
  lang_ticket_filter_end_time: 'End Time',
  lang_ticket_filter_cancel: 'Cancel',
  lang_ticket_filter_select_date: 'Chose Time',
  lang_ticket_filter_input: 'Please input...',
  lang_ticket_clear_filter: 'Clear Filter Condition',
  lang_ticket_filter: 'Search',

  lang_ticket_detail_log: 'Work Logs',
  lang_ticket_detail_add_log: 'Create Work Log',
  lang_ticket_detail_edit_log: 'Edit Work Log',
  lang_ticket_detail_del_log: 'Delete Work Log',
  lang_ticket_detail_create_time: 'Create',
  lang_ticket_detail_task: 'Description',
  lang_ticket_detail_assets: 'Equipment',

  lang_ticket_detail_approved: 'Approve',
  lang_ticket_detail_write_log: 'Add Work Log',
  lang_ticket_detail_begin_execute: 'Execute',
  lang_ticket_detail_submit_ticket: 'Submit',
  lang_ticket_log_del_confirm: 'Are you sure to delete it？',
  lang_ticket_log_del_img_confirm: 'Are you sure to delete it？',
  lang_ticket_log_del_ok: 'Delete',
  lang_ticket_detail_share: 'Share',
  lang_ticket_detail_edit: 'Edit',
  lang_ticket_detail: 'Work Details',
  lang_ticket_detail_ignore: 'Ignore',
  lang_ticket_detail_ignore_confirm: 'It cannot be operated after being ignored.Are you sure to ignore it?',
  lang_ticket_detail_ticketId: 'Work ID',
  lang_ticket_submit_invalid: 'Unable to submit, please add work log and try again',
  lang_ticket_detail_reject_reason: 'Cause of Reverted',
  lang_ticket_execute_toast: 'Starting, please add work log',
  lang_ticket_submit_toast: 'Submitted Successfully',
  lang_ticket_close_toast: 'Approved and task is complete',
  lang_ticket_close_confirm: 'Are you sure to complete it?',

  lang_ticket_detail_change_time: 'Edit Execute Time',
  lang_ticket_detail_change_executors: 'Edit Executor',

  lang_ticket_diagnose: 'Smart Diagnosis Works',

  lang_ticket_to: 'to',


  lang_alert_title: 'Notice',
  lang_alert_ok: 'Ok',

  lang_ticket_select_time_invalid: 'The start time cannot be later than the end time',

  lang_toolbar_ok: 'Done',
  lang_toolbar_submit: 'Submit',

  lang_image_picker_cancel: 'Cancel',
  lang_image_picker_accept: 'Allow',
  lang_image_picker_accept_msg: 'Please allow this App to get access your camera in your phone\'s "Settings"',
  lang_image_picker_access_storage: 'Please allow this App to get read and write your storage in your phone\'s "Settings"',
  lang_image_picker_open_photos: 'Open the Camera',
  lang_image_picker_from_photos: 'Get it from your photo album',
  lang_image_picker_title: 'Photo',
  lang_image_picker_access_photos: 'Please allow this App to get access your photos in your phone\'s "Settings"',
  lang_image_picker_read_storage: 'Please allow this App to access your storage in your phone\'s "Settings"',
  lang_image_picker_no_photos: 'No Photos',
  lang_image_take_photo: 'Take Photos',

  lang_today: 'today',

  lang_network_error: 'Failed to load, please check your network setting',
  lang_server_error: 'Server exception',
  lang_http_no_content: 'No Content',
  lang_http_401: 'Unauthorized',

  //----------------添加盘盈设备页面文字提取
  lang_add_device_group_photo: 'Photo',
  lang_add_device_group_basic: 'Basic Info',
  lang_add_device_basic_name: 'Name',
  lang_add_device_basic_num: 'Number',
  lang_add_device_basic_place: 'Store',
  lang_add_device_group_params: 'Parameters',
  lang_add_device_params_class: 'Class',
  lang_add_device_params_type: 'Type',
  lang_add_device_params_model: 'Model',
  lang_add_device_api_tpl_error: 'Failed to get template data!',
  lang_add_device_api_tpl2_error: 'Failed to get hierarchy template data!',
  lang_add_device_api_submit_error: 'Failed to save!',
  lang_add_device_submit_valid: 'Name, Number, Class, Type, Model, Photo of the asset cannot be empty',
  lang_add_device_row_select: 'Please select',
  lang_add_device_image_uploading: 'Uploading Image, please wait',
  lang_add_device_title: 'Gain',
  lang_add_device_submit_button: 'Submit',
  lang_add_device_options: '(Optional)',

  lang_scan_page_alert_error_title: 'Recognition Failure',
  lang_scan_page_alert_error_content: 'Unrecognizable QR code',
  lang_scan_page_alert_error_button: 'Confirm',
  lang_scan_page_light: 'Light',
  lang_scan_page_light_on: 'On',
  lang_scan_page_light_off: 'Off',
  lang_scan_tip: 'Please scan the QR code on the device',

  lang_scan_result_page_status_tag1: 'In Use',
  lang_scan_result_page_status_tag2: 'Missing',
  lang_scan_result_page_status_tag3: 'Idle',
  lang_scan_result_page_status_tag4: 'In Allocation',
  lang_scan_result_page_status_tag5: 'Under Repair',
  lang_scan_result_page_status_tag6: 'Retired',
  lang_scan_result_page_status_tag7: 'Retiring',

  lang_scan_result_page_tag1: 'Fault',
  lang_scan_result_page_tag2: 'Marked',

  lang_scan_result_submit_success_tip: 'Inventory result submitted successfully!',
  lang_scan_result_submit_error_tip: 'Inventory Failure, please check parameters!',
  lang_scan_result_label1: 'Result',
  lang_scan_result_label2: 'Checked',
  lang_scan_result_label3: 'Loss',
  lang_scan_result_label4: 'Tag',
  lang_scan_result_label5: '(Optional)',
  lang_scan_result_label6: 'Please input notes(Optional)',
  lang_scan_result_label7: 'In query',
  lang_scan_result_label8: 'Result',
  lang_scan_result_label9: 'Confirm',
  lang_scan_result_label10: 'Number',


  lang_ticket_detail_add_device: 'Add Asset',
  lang_ticket_detail_scan_device: 'QR Code Scan',
  lang_ticekt_detail_info_exception: 'Inventory gain asset cannot be created due to current ticket error',
  lang_ticket_detail_not_include_device: 'This asset is not in the scope of this inventory',
  lang_ticket_detail_delete_device_confirm: 'Delete this inventory gain asset?',
  lang_ticket_detail_set_status_error: 'Failed to set status!',
  lang_ticket_detail_submit_check1: 'Inventory Gain Assets Automatically Added',
  lang_ticket_detail_submit_check2: 'Unchecked Assets Automatically Marked as Loss and Created as Retirement Task',
  lang_ticket_detail_submit_check3: 'Inventory Loss Assets Automatically Created as Retirement Task',
  lang_ticket_detail_submit_check4: 'Fault Assets Automatically Created as Repair Ticket',
  lang_ticket_detail_submit_check5: 'Marked Assets Automatically Created as Retirement Task',
  lang_ticket_detail_execute_time: 'Time',
  lang_ticket_detail_status_expired: 'Overdue',
  lang_ticket_detail_execute_person: 'Executor',
  lang_ticket_detail_device_tab1: 'All',
  lang_ticket_detail_device_tab2: 'Unchecked',
  lang_ticket_detail_device_tab3: 'Checked',
  lang_ticket_detail_device_tab5: 'Gain',
  lang_ticket_detail_device_tab4: 'Loss',
  lang_ticket_detail_submit_success: 'Submit Success',
  lang_ticket_detail_device_check: 'Inventory',

  lang_ticket_execute_time:'Execute Time',
  lang_ticket_location:'Location',

  lang_single_select_search_no_result: 'No result',
  lang_single_select_manual_input: 'Manual Input',
  lang_single_select_input_keyword: 'Input Keyword',

  lang_add_device_success_tip:'Create Inventory Gain Asset Successfully!',
  lang_add_scrap_ticket_tip:'Create Retirement Record Successfully!',
  lang_ticket_list_tab_undone:'Undone',
  lang_ticket_list_tab_done:'Done',
};
