export default {
  lang_loading_waiting: 'Loading, please wait...',
  lang_clear_filter: 'Clear Filter Condition',
  lang_empty_data: 'No Data',
  lang_ticket_list_no_permission: 'You have no authorization to operate, please contact the administrator',
  lang_load_more: 'Loading, please wait...',

  lang_status_1: 'To Do',
  lang_status_2: 'In Progress',
  lang_status_3: 'Submitted',
  lang_status_4: 'Reverted',
  lang_status_5: 'Completed',
  lang_status_6: 'Ignored',

  lang_ticket_status_type: ['To Do', 'In Progress', 'Submitted', 'Reverted', 'Completed', 'Ignored'],
  lang_ticket_name: 'Work Name',
  lang_ticket_filter_time: 'Time',
  lang_ticket_filter_ok: 'confirm',
  lang_ticket_filter_reset: 'Reset',
  lang_ticket_filter_status: 'Status',
  lang_ticket_filter_start_time: 'Start Time',
  lang_ticket_filter_end_time: 'End Time',
  lang_ticket_filter_cancel: 'Cancel',
  lang_ticket_filter_select_date: 'Chose Time',
  lang_ticket_filter_input: 'Please input...',
  lang_ticket_clear_filter: 'Clear Filter Condition',
  lang_ticket_filter: 'Search',

  lang_ticket_detail_log: 'Work Logs',
  lang_ticket_detail_add_log: 'Create Work Log',
  lang_ticket_detail_edit_log: 'Edit Work Log',
  lang_ticket_detail_del_log: 'Delete Work Log',
  lang_ticket_detail_create_time: 'Create',
  lang_ticket_detail_task: 'Description',
  lang_ticket_detail_assets: 'Equipment',

  lang_ticket_detail_approved: 'Approve',
  lang_ticket_detail_write_log: 'Add Work Log',
  lang_ticket_detail_begin_execute: 'Execute',
  lang_ticket_detail_submit_ticket: 'Submit',
  lang_ticket_log_del_confirm: 'Are you sure to delete it？',
  lang_ticket_log_del_img_confirm: 'Are you sure to delete it？',
  lang_ticket_log_del_ok: 'Delete',
  lang_ticket_detail_share: 'Share',
  lang_ticket_detail_edit: 'Edit',
  lang_ticket_detail: 'Work Details',
  lang_ticket_detail_ignore: 'Ignore',
  lang_ticket_detail_ignore_confirm: 'It cannot be operated after being ignored.Are you sure to ignore it?',
  lang_ticket_detail_ticketId: 'Work ID',
  lang_ticket_submit_invalid: 'Unable to submit, please add work log and try again',
  lang_ticket_detail_reject_reason: 'Cause of Reverted',
  lang_ticket_execute_toast: 'Starting, please add work log',
  lang_ticket_submit_toast: 'Submitted Successfully',
  lang_ticket_close_toast: '审批通过，任务已完成',
  lang_ticket_close_confirm: 'Are you sure to complete it?',

  lang_ticket_detail_change_time: 'Edit Execute Time',
  lang_ticket_detail_change_executors: 'Edit Executor',

  lang_ticket_diagnose: 'Smart Diagnosis Works',

  lang_ticket_to: 'to',


  lang_alert_title: 'Notice',
  lang_alert_ok: 'Ok',

  lang_ticket_select_time_invalid: 'The start time cannot be later than the end time',

  lang_toolbar_ok: 'Done',
  lang_toolbar_submit: 'Submit',

  lang_image_picker_cancel: 'Cancel',
  lang_image_picker_accept: 'Allow',
  lang_image_picker_accept_msg: 'Please allow this App to get access your camera in your phone\'s "Settings"',
  lang_image_picker_access_storage: 'Please allow this App to get read and write your storage in your phone\'s "Settings"',
  lang_image_picker_open_photos: 'Open the Camera',
  lang_image_picker_from_photos: 'Get it from your photo album',
  lang_image_picker_title: 'Photo',
  lang_image_picker_access_photos: 'Please allow this App to get access your photos in your phone\'s "Settings"',
  lang_image_picker_read_storage: 'Please allow this App to access your storage in your phone\'s "Settings"',
  lang_image_picker_no_photos: 'No Photos',
  lang_image_take_photo: 'Take Photos',

  lang_today: 'today',

  lang_network_error: 'Failed to load, please check your network setting',
  lang_server_error: 'Server exception',
  lang_http_no_content: 'No Content',
  lang_http_401: 'Unauthorized',

  //----------------添加盘盈设备页面文字提取
  lang_add_device_group_photo: '照片',
  lang_add_device_group_basic: '基本信息',
  lang_add_device_basic_name: '产品名称',
  lang_add_device_basic_num: '产品编号',
  lang_add_device_basic_place: '所在门店',
  lang_add_device_group_params: '参数配置',
  lang_add_device_params_class: '设备总称',
  lang_add_device_params_type: '设备类型',
  lang_add_device_params_model: '设备型号',
  lang_add_device_api_tpl_error: '获取模板数据失败！',
  lang_add_device_api_tpl2_error: '获取层级模板数据失败！',
  lang_add_device_api_submit_error: '保存失败!',
  lang_add_device_submit_valid: '资产名称、编号、总称、类型、型号、图片都不能为空',
  lang_add_device_row_select: '请选择',
  lang_add_device_image_uploading: '图片上传中，请稍后...',
  lang_add_device_title: '盘盈',
  lang_add_device_submit_button: '保存',
  lang_add_device_options: '(选填)',

  lang_scan_page_alert_error_title: '识别失败',
  lang_scan_page_alert_error_content: '非系统可识别的二维码',
  lang_scan_page_alert_error_button: '知道了',
  lang_scan_page_light: '手电筒',
  lang_scan_page_light_on: '打开',
  lang_scan_page_light_off: '关闭',
  lang_scan_tip: '对准设备上的二维码',

  lang_scan_result_page_status_tag1: '在用',
  lang_scan_result_page_status_tag2: '缺失',
  lang_scan_result_page_status_tag3: '闲置',
  lang_scan_result_page_status_tag4: '调拨中',
  lang_scan_result_page_status_tag5: '维修中',
  lang_scan_result_page_status_tag6: '报废',
  lang_scan_result_page_status_tag7: '清理中',

  lang_scan_result_page_tag1: '故障资产',
  lang_scan_result_page_tag2: '待清理资产',
  lang_scan_result_submit_success_tip: '盘点结果提交成功！',
  lang_scan_result_submit_error_tip: '盘点失败，请检查参数！',
  lang_scan_result_label1: '盘点结果',
  lang_scan_result_label2: '已盘',
  lang_scan_result_label3: '盘亏',
  lang_scan_result_label4: '标签',
  lang_scan_result_label5: '(选填)',
  lang_scan_result_label6: '请输入备注（选填）',
  lang_scan_result_label7: '查询中',
  lang_scan_result_label8: '盘点结果',
  lang_scan_result_label9: '确认盘点',
  lang_scan_result_label10: '编号',

  lang_ticket_detail_add_device: '新增盘盈',
  lang_ticket_detail_scan_device: '扫码盘点',
  lang_ticekt_detail_info_exception: '当前工单异常，无法创建盘盈设备',
  lang_ticket_detail_not_include_device: '该资产不在本次盘点范围内',
  lang_ticket_detail_delete_device_confirm: '确定删除这个盘盈设备吗？',
  lang_ticket_detail_set_status_error: '设置状态失败！',
  lang_ticket_detail_submit_check1: '盘盈资产自动新增入库',
  lang_ticket_detail_submit_check2: '未盘资产自动盘亏处理并创建清理报废单',
  lang_ticket_detail_submit_check3: '盘亏资产自动创建清理报废单',
  lang_ticket_detail_submit_check4: '标记为故障的资产自动创建报修单',
  lang_ticket_detail_submit_check5: '标记为待清理的资产自动创建清理报废单',
  lang_ticket_detail_execute_time: '执行时间',
  lang_ticket_detail_status_expired: '逾期',
  lang_ticket_detail_execute_person: '执行人',
  lang_ticket_detail_device_tab1: '全部',
  lang_ticket_detail_device_tab2: '未盘',
  lang_ticket_detail_device_tab3: '已盘',
  lang_ticket_detail_device_tab4: '盘亏',
  lang_ticket_detail_device_tab5: '盘盈',
  lang_ticket_detail_submit_success: '提交成功',
  lang_ticket_detail_device_check: '盘点',

  lang_ticket_execute_time:'Execute Time',
  lang_ticket_location:'Location',

  lang_single_select_search_no_result: '搜索无结果',
  lang_single_select_manual_input: '手动输入',
  lang_single_select_input_keyword: '输入关键字',
};
