export default {
  lang_loading_waiting: '加载中，请稍候...',
  lang_clear_filter: '清空筛选条件',
  lang_empty_data: '暂无数据',
  lang_ticket_list_no_permission: '您没有这一项的操作权限，请联系系统管理员',
  lang_load_more: '加载中，请稍后...',

  lang_status_1: '待执行',
  lang_status_2: '执行中',
  lang_status_3: '待审批',
  lang_status_4: '已驳回',
  lang_status_5: '已完成',
  lang_status_6: '已忽略',

  lang_ticket_status_type: ['待执行', '执行中', '待审批', '已驳回', '已完成', '已忽略'],
  lang_ticket_name: '工单名称',
  lang_ticket_filter_time: '时间',
  lang_ticket_filter_ok: '确定',
  lang_ticket_filter_reset: '重置',
  lang_ticket_filter_status: '工单状态',
  lang_ticket_filter_start_time: '开始时间',
  lang_ticket_filter_end_time: '结束时间',
  lang_ticket_filter_cancel: '取消',
  lang_ticket_filter_select_date: '选择日期',
  lang_ticket_filter_input: '请输入',
  lang_ticket_clear_filter: '清空筛选条件',
  lang_ticket_filter: '工单筛选',

  lang_ticket_detail_log: '日志',
  lang_ticket_detail_add_log: '创建日志',
  lang_ticket_detail_edit_log: '编辑日志',
  lang_ticket_detail_del_log: '删除日志',
  lang_ticket_detail_create_time: '创建于',
  lang_ticket_detail_task: '任务描述',
  lang_ticket_detail_assets: '资产',

  lang_ticket_detail_approved: '审批通过',
  lang_ticket_detail_write_log: '写日志',
  lang_ticket_detail_begin_execute: '开始执行',
  lang_ticket_detail_submit_ticket: '提交审批',
  lang_ticket_log_del_confirm: '删除这条日志吗？',
  lang_ticket_log_del_img_confirm: '删除这张图片吗？',
  lang_ticket_log_del_ok: '删除',
  lang_ticket_detail_share: '分享',
  lang_ticket_detail_edit: '编辑',
  lang_ticket_detail: '工单详情',
  lang_ticket_detail_ignore: '忽略',
  lang_ticket_detail_ignore_confirm: '忽略后，⼯单将⽆法进⾏任何操作，确认忽略?',
  lang_ticket_detail_ticketId: '工单ID',
  lang_ticket_submit_invalid: '无法提交，请添加工单日志后重试',
  lang_ticket_detail_reject_reason: '驳回原因',
  lang_ticket_execute_toast: '开始执行，请添加工单日志',
  lang_ticket_submit_toast: '工单提交成功',
  lang_ticket_close_toast: '审批通过，任务已完成',
  lang_ticket_close_confirm: '是否确认关闭工单?',

  lang_ticket_detail_change_time: '修改执行时间',
  lang_ticket_detail_change_executors: '修改执行人',

  lang_ticket_diagnose: '诊断工单',

  lang_ticket_to: '至',


  lang_alert_title: '提示',
  lang_alert_ok: '好',

  lang_ticket_select_time_invalid: '开始时间不能晚于结束时间',

  lang_toolbar_ok: '完成',
  lang_toolbar_submit: '提交',

  lang_image_picker_cancel: '取消',
  lang_image_picker_accept: '允许',
  lang_image_picker_accept_msg: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的摄像头',
  lang_image_picker_access_storage: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用读写您的存储空间',
  lang_image_picker_open_photos: '打开照相机',
  lang_image_picker_from_photos: '从手机相册获取',
  lang_image_picker_title: '图片',
  lang_image_picker_access_photos: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的相册',
  lang_image_picker_read_storage: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的存储',
  lang_image_picker_no_photos: '暂无图片',
  lang_image_take_photo: '拍照',

  lang_today: '今',

  lang_network_error: '加载失败，请检查您的网络设置',
  lang_server_error: '服务器异常',
  lang_http_no_content: '无内容',
  lang_http_401: '未授权',

  //----------------添加盘盈设备页面文字提取
  lang_add_device_group_photo: '照片',
  lang_add_device_group_basic: '基本信息',
  lang_add_device_basic_name: '产品名称',
  lang_add_device_basic_num: '产品编号',
  lang_add_device_basic_place: '所在门店',
  lang_add_device_group_params: '参数配置',
  lang_add_device_params_class: '设备总称',
  lang_add_device_params_type: '设备类型',
  lang_add_device_params_model: '设备型号',
  lang_add_device_api_tpl_error: '获取模板数据失败！',
  lang_add_device_api_tpl2_error: '获取层级模板数据失败！',
  lang_add_device_api_submit_error: '保存失败!',
  lang_add_device_submit_valid: '资产名称、编号、总称、类型、型号、图片都不能为空',
  lang_add_device_row_select: '请选择',
  lang_add_device_image_uploading: '图片上传中，请稍后...',
  lang_add_device_title: '盘盈',
  lang_add_device_submit_button: '保存',
  lang_add_device_options: '(选填)',

  lang_scan_page_alert_error_title: '识别失败',
  lang_scan_page_alert_error_content: '非系统可识别的二维码',
  lang_scan_page_alert_error_button: '知道了',
  lang_scan_page_light: '手电筒',
  lang_scan_page_light_on: '打开',
  lang_scan_page_light_off: '关闭',
  lang_scan_tip: '对准设备上的二维码',

  lang_scan_result_page_status_tag1: '在用',
  lang_scan_result_page_status_tag2: '缺失',
  lang_scan_result_page_status_tag3: '闲置',
  lang_scan_result_page_status_tag4: '调拨中',
  lang_scan_result_page_status_tag5: '维修中',
  lang_scan_result_page_status_tag6: '报废',
  lang_scan_result_page_status_tag7: '清理中',

  lang_scan_result_page_tag1: '故障资产',
  lang_scan_result_page_tag2: '待清理资产',
  lang_scan_result_submit_success_tip: '盘点结果提交成功！',
  lang_scan_result_submit_error_tip: '盘点失败，请检查参数！',
  lang_scan_result_label1: '盘点结果',
  lang_scan_result_label2: '已盘',
  lang_scan_result_label3: '盘亏',
  lang_scan_result_label4: '标签',
  lang_scan_result_label5: '(选填)',
  lang_scan_result_label6: '请输入备注（选填）',
  lang_scan_result_label7: '查询中',
  lang_scan_result_label8: '盘点结果',
  lang_scan_result_label9: '确认盘点',
  lang_scan_result_label10: '编号',

  lang_ticket_detail_add_device: '新增盘盈',
  lang_ticket_detail_scan_device: '扫码盘点',
  lang_ticekt_detail_info_exception: '当前工单异常，无法创建盘盈设备',
  lang_ticket_detail_not_include_device: '该资产不在本次盘点范围内',
  lang_ticket_detail_delete_device_confirm: '确定删除这个盘盈设备吗？',
  lang_ticket_detail_set_status_error: '设置状态失败！',
  lang_ticket_detail_submit_check1: '盘盈资产自动新增入库',
  lang_ticket_detail_submit_check2: '未盘资产自动盘亏处理并创建清理报废单',
  lang_ticket_detail_submit_check3: '盘亏资产自动创建清理报废单',
  lang_ticket_detail_submit_check4: '标记为故障的资产自动创建报修单',
  lang_ticket_detail_submit_check5: '标记为待清理的资产自动创建清理报废单',
  lang_ticket_detail_execute_time: '执行时间',
  lang_ticket_detail_status_expired: '逾期',
  lang_ticket_detail_execute_person: '执行人',
  lang_ticket_detail_device_tab1: '全部',
  lang_ticket_detail_device_tab2: '未盘',
  lang_ticket_detail_device_tab3: '已盘',
  lang_ticket_detail_device_tab4: '盘亏',
  lang_ticket_detail_device_tab5: '盘盈',
  lang_ticket_detail_submit_success: '提交成功',
  lang_ticket_detail_device_check: '盘点',

  lang_ticket_execute_time:'建议执行时间',
  lang_ticket_location:'位置',

  lang_single_select_search_no_result: '搜索无结果',
  lang_single_select_manual_input: '手动输入',
  lang_single_select_input_keyword: '输入关键字',

  lang_add_device_success_tip:'创建盘盈设备成功!',
  lang_add_scrap_ticket_tip:'创建报废单成功！',
  lang_ticket_list_tab_undone:'未完成',
  lang_ticket_list_tab_done:'已完成',
};
