export default {
  lang_loading_waiting: '加载中，请稍候...',
  lang_clear_filter: '清空筛选条件',
  lang_empty_data: '暂无数据',
  lang_ticket_list_no_permission: '您没有这一项的操作权限，请联系系统管理员',
  lang_load_more: '加载中，请稍后...',

  lang_status_1: '未开始',
  lang_status_2: '执行中',
  lang_status_3: '已提交',
  lang_status_4: '已驳回',
  lang_status_5: '已关闭',
  lang_status_6: '已忽略',

  lang_ticket_status_type: ['未开始', '执行中', '已提交', '已驳回', '已关闭', '已忽略'],
  lang_ticket_name: '工单名称',
  lang_ticket_filter_time: '时间',
  lang_ticket_filter_ok: '确定',
  lang_ticket_filter_reset: '重置',
  lang_ticket_filter_status: '工单状态',
  lang_ticket_filter_start_time: '开始时间',
  lang_ticket_filter_end_time: '结束时间',
  lang_ticket_filter_cancel: '取消',
  lang_ticket_filter_select_date: '选择日期',
  lang_ticket_filter_input: '请输入',
  lang_ticket_clear_filter: '清空筛选条件',
  lang_ticket_filter: '工单筛选',

  lang_ticket_detail_log: '日志',
  lang_ticket_detail_add_log: '创建日志',
  lang_ticket_detail_edit_log: '编辑日志',
  lang_ticket_detail_del_log: '删除日志',
  lang_ticket_detail_create_time: '创建于',
  lang_ticket_detail_task: '任务描述',
  lang_ticket_detail_assets: '资产',

  lang_ticket_detail_approved: '审批通过',
  lang_ticket_detail_write_log: '写日志',
  lang_ticket_detail_begin_execute: '开始执行',
  lang_ticket_detail_submit_ticket: '提交审批',
  lang_ticket_log_del_confirm: '删除这条日志吗？',
  lang_ticket_log_del_img_confirm: '删除这张图片吗？',
  lang_ticket_log_del_ok: '删除',
  lang_ticket_detail_share: '分享',
  lang_ticket_detail_edit: '编辑',
  lang_ticket_detail: '工单详情',
  lang_ticket_detail_ignore: '忽略',
  lang_ticket_detail_ignore_confirm: '忽略后，⼯单将⽆法进⾏任何操作，确认忽略?',
  lang_ticket_detail_ticketId: '工单ID',
  lang_ticket_submit_invalid: '无法提交，请添加工单日志后重试',
  lang_ticket_detail_reject_reason: '驳回原因',
  lang_ticket_execute_toast: '开始执行，请添加工单日志',
  lang_ticket_submit_toast: '工单提交成功',
  lang_ticket_close_toast: '审批通过，任务已完成',
  lang_ticket_close_confirm: '是否确认关闭工单?',

  lang_ticket_detail_change_time: '修改执行时间',
  lang_ticket_detail_change_executors: '修改执行人',

  lang_ticket_diagnose: '诊断工单',

  lang_ticket_to: '至',


  lang_alert_title: '提示',
  lang_alert_ok: '好',

  lang_ticket_select_time_invalid: '开始时间不能晚于结束时间',

  lang_toolbar_ok: '完成',
  lang_toolbar_submit: '提交',

  lang_image_picker_cancel: '取消',
  lang_image_picker_accept: '允许',
  lang_image_picker_accept_msg: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的摄像头',
  lang_image_picker_access_storage: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用读写您的存储空间',
  lang_image_picker_open_photos: '打开照相机',
  lang_image_picker_from_photos: '从手机相册获取',
  lang_image_picker_title: '图片',
  lang_image_picker_access_photos: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的相册',
  lang_image_picker_read_storage: '请在手机的' + '"' + '设置' + '"' + '中，允许此应用访问您的存储',
  lang_image_picker_no_photos: '暂无图片',
  lang_image_take_photo: '拍照',

  lang_today: '今',

  lang_network_error: '加载失败，请检查您的网络设置',
  lang_server_error: '服务器异常',
  lang_http_no_content: '无内容',
  lang_http_401: '未授权'
};
